services:
  - type: web
    name: blog
    runtime: docker
    region: singapore
    plan: free
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: DB_PATH
        value: /app/data/blog.db
    dockerfilePath: ./Dockerfile
    disk:
      name: sqlite-data
      mountPath: /app/data
      sizeGB: 1
